### ISSUE TITLE
Mongo_Adapter: build events override non-Mongo-related DLLs, which can cause compilation errors

### ISSUE THREAD

**Issue by alelom** [BHoM/Mongo_Toolkit#161] opened 2022-08-16 12:40 UTC
#### Description:

The build events in Mongo_Adapter include non-mongo DLLs copies because of this line:
```
xcopy "$(TargetDir)*.dll"  "C:\ProgramData\BHoM\Assemblies"
```

This had more than once caused me trouble in compilation where non-mongo DLLs were overridden to a non-desirable version (e.g. BHoM_Adapter).

#### Steps to reproduce:

Compile Mongo_Adapter.

#### Expected behaviour:

Only needed DLLs should be copied by Mongo_Adapter.

#### Test file(s):

See above.

**Comment by FraserGreenroyd** [comment] 2024-01-04 17:26
Having reviewed this as part of historic issue review, and the associated #162 PR which came with it, and the issue was actually caused by `copylocal` being set to true for BHoM DLLs which were used by Mongo Toolkit. This has since been resolved and is kept in check by `project-compliance` on pull requests, so I'm closing this issue as complete 😄

**Closed by FraserGreenroyd** 2024-01-04 17:26 UTC
Labels: type:bug, type:compliance
